name = "roboc"
version = "1.0.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glint = ">= 1.2.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
glenvy = ">= 2.0.1 and < 3.0.0"
openrouter_client = { git = "https://gitea2.flowerbox.house/dtw/openrouter_client.git", ref = "99974f35ddea" }
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
