name = "roboc"
version = "1.0.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glint = ">= 1.2.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
glenvy = ">= 2.0.1 and < 3.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
in = ">= 1.1.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
oas = ">= 7.3.0 and < 8.0.0"
child_process = ">= 1.1.1 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleescript = ">= 1.5.2 and < 2.0.0"
